/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/dashboard/': RouteRecordInfo<'/dashboard/', '/dashboard', Record<never, never>, Record<never, never>>,
    '/dashboard/adapters/': RouteRecordInfo<'/dashboard/adapters/', '/dashboard/adapters', Record<never, never>, Record<never, never>>,
    '/dashboard/auth/login': RouteRecordInfo<'/dashboard/auth/login', '/dashboard/auth/login', Record<never, never>, Record<never, never>>,
    '/dashboard/bots/': RouteRecordInfo<'/dashboard/bots/', '/dashboard/bots', Record<never, never>, Record<never, never>>,
    '/dashboard/commands/': RouteRecordInfo<'/dashboard/commands/', '/dashboard/commands', Record<never, never>, Record<never, never>>,
    '/dashboard/database/': RouteRecordInfo<'/dashboard/database/', '/dashboard/database', Record<never, never>, Record<never, never>>,
    '/dashboard/messages/': RouteRecordInfo<'/dashboard/messages/', '/dashboard/messages', Record<never, never>, Record<never, never>>,
    '/dashboard/plugins/': RouteRecordInfo<'/dashboard/plugins/', '/dashboard/plugins', Record<never, never>, Record<never, never>>,
  }
}
